#
# This workflow sets the status check `synthetics-stack-e2e` instantly to 'failure'
# the synthetics-stack-e2e.yml is triggered with a PR comment and is responsible for setting it to success or failure.
#
name: synthetics # This name needs to be the same as in synthetic-stack-e2e.yml

on:
  pull_request_target:
    paths:
      - "x-pack/plugins/synthetics/**"

jobs:
  init-synthetics-stack-e2e: # This name needs to be the same as in synthetic-stack-e2e.yml
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Create commit status
        uses: actions/github-script@v6
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
        with:
          script: |    
            const { owner, repo } = context.repo;
            github.rest.repos.createCommitStatus({
              owner,
              repo,
              context: "synthetics-stack-e2e",
              sha: process.env.SHA,
              state: 'pending',
            });
