#
# This workflow is triggered by a comment on a PR and runs the synthetics stack e2e tests
# It is responsible for setting the status check `synthetics-stack-e2e` to success or failure,
# which was set to failure by the synthetics-stack-e2e-init.yml workflow.
#
---
name: synthetics # This name needs to be the same as in synthetic-stack-e2e-init.yml

on:
  check_run:
    types:
      - requested_action
#  issue_comment:
#    types:
#      - created

jobs:
  synthetics-stack-e2e:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - run: echo '${{ toJSON(github.event) }}'


#  trigger-synthetics-stack-e2e: # This name needs to be the same as in synthetic-stack-e2e-init.yml
#    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/synthetics-stack-e2e') }}
#    runs-on: ubuntu-latest
#    permissions:
#      pull-requests: read
#      checks: write
#    steps:
#      - uses: reakaleek/apm-pipeline-library/.github/actions/run-synthetics-stack-e2e@feature/synthetics-stack-e2e-action
#        with:
#          vault-url: ${{ secrets.OBLT_VAULT_ADDR }}
#          vault-role-id: ${{ secrets.OBLT_VAULT_ROLE_ID }}
#          vault-secret-id: ${{ secrets.OBLT_VAULT_SECRET_ID }}
