#
# This workflow is triggered by a comment on a PR and runs the synthetics stack e2e tests
# It is responsible for setting the status check `synthetics-stack-e2e` to success or failure,
# which was set to failure by the synthetics-stack-e2e-init.yml workflow.
#
---
name: synthetics # This name needs to be the same as in synthetic-stack-e2e-init.yml

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    paths:
      - "x-pack/plugins/synthetics/**"

## Cancel any previous runs of this workflow if it's a comment from the same PR
#concurrency:
#  group: ${{ github.workflow }}-${{ github.comment && format('comment-{0}', github.even.issue.number) || github.event.pull_request.head.sha }}
#  cancel-in-progress: ${{ github.event.comment && true || false }}

jobs:
  synthetics-stack-e2e:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write
    steps:
      - uses: reakaleek/apm-pipeline-library/.github/actions/synthetics-stack-e2e@feature/synthetics-stack-e2e-action
        with:
          vault-url: ${{ secrets.OBLT_VAULT_ADDR }}
          vault-role-id: ${{ secrets.OBLT_VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.OBLT_VAULT_SECRET_ID }}
