#
# This workflow sets the status check `synthetics-stack-e2e` instantly to 'failure'
# the synthetics-stack-e2e.yml is triggered with a PR comment and is responsible for setting it to success or failure.
#
name: synthetics # This name needs to be the same as in synthetic-stack-e2e.yml

on:
  pull_request_target:
    paths:
      - "x-pack/plugins/synthetics/**"

jobs:
  synthetics-stack-e2e: # This name needs to be the same as in synthetic-stack-e2e.yml
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Create check
        uses: actions/github-script@v6
        id: create-check
        env:
          PR_NUMBER: ${{ inputs.pr-number }}
        with:
          script: |
            const { owner, repo } = context.repo;
            await github.rest.checks.create({
              owner,
              repo,
              head_sha: process.env.GITHUB_SHA,
              status: 'queued',
              name: "synthetics-stack-e2e",
              conclusion: 'action_required',
            });
